FROM buildpack-deps:bullseye


# skip installing gem documentation
RUN set -eux; \
	mkdir -p /usr/local/etc; \
	{ \
		echo 'install: --no-document'; \
		echo 'update: --no-document'; \
	} >> /usr/local/etc/gemrc

#ENV LANG C.UTF-8
ENV LANG C.UTF-8
ENV RUBY_MAJOR 2.3
ENV RUBY_VERSION 2.3.1
ENV BUNDLER_VERSION=2.0.1
ENV RUBY_DOWNLOAD_SHA256 6725b5534d5a3a21ec4f14d6d7b9921a0d00d08acb88fd04cd50b47b70496338
RUN echo 'deb http://security.debian.org/debian-security stretch/updates main' >> /etc/apt/sources.list \
    && echo 'deb http://ftp.cn.debian.org/debian stretch main ' >> /etc/apt/sources.list \
# some of ruby's build scripts are written in ruby
#   we purge system ruby later to make sure our final image uses what we just built
RUN set -eux; \
	\
	savedAptMark="$(apt-mark showmanual)"; \
	apt-get update; \
	apt-get install -y --no-install-recommends \
		bison \
		dpkg-dev \
		libgdbm-dev \
                libgeos-dev \
		ruby2.3 ; \
        apt-get install -y libssl1.0-dev; \
	rm -rf /var/lib/apt/lists/*; \
	\
	wget -O ruby.tar.xz "https://cache.ruby-lang.org/pub/ruby/${RUBY_MAJOR%-rc}/ruby-$RUBY_VERSION.tar.xz"; \
	echo "$RUBY_DOWNLOAD_SHA256 *ruby.tar.xz" | sha256sum --check --strict; \
	\
	mkdir -p /usr/src/ruby; \
	tar -xJf ruby.tar.xz -C /usr/src/ruby --strip-components=1; \
	rm ruby.tar.xz; \
	\
	cd /usr/src/ruby; \
	\
# hack in "ENABLE_PATH_CHECK" disabling to suppress:
#   warning: Insecure world writable dir
	{ \
		echo '#define ENABLE_PATH_CHECK 0'; \
		echo; \
		cat file.c; \
	} > file.c.new; \
	mv file.c.new file.c; \
	\
	autoconf; \
	gnuArch="$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)"; \
	./configure \
		--build="$gnuArch" \
		--disable-install-doc \
		--enable-shared \
	; \
	make -j "$(nproc)"; \
	make install; \
	\
	apt-get update; \
        apt-get install -y libcurl4-openssl-dev \
                        default-libmysqlclient-dev; \
        \
	apt-mark auto '.*' > /dev/null; \
	apt-mark manual $savedAptMark > /dev/null; \
	find /usr/local -type f -executable -not \( -name '*tkinter*' \) -exec ldd '{}' ';' \
		| awk '/=>/ { print $(NF-1) }' \
		| sort -u \
		| grep -vE '^/usr/local/lib/' \
		| xargs -r dpkg-query --search \
		| cut -d: -f1 \
		| sort -u \
		| xargs -r apt-mark manual \
	; \
	apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
	\
	cd /; \
	rm -r /usr/src/ruby; \
# verify we have no "ruby" packages installed
	if dpkg -l | grep -i ruby; then exit 1; fi; \
	[ "$(command -v ruby)" = '/usr/local/bin/ruby' ]; \
# rough smoke test
	ruby --version; \
	gem --version; \
	gem install bundler --version "$BUNDLER_VERSION"; \
        bundle --version; \
        apt-get install -y libssl1.0-dev libcurl4-gnutls-dev gnupg2; \
        gem install passenger; \
        passenger-install-nginx-module --auto; \
        wget http://www.linuxidc.com/files/repo/google-chrome.list -P /etc/apt/sources.list.d/ ; \
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub  | apt-key add - ; \
        apt-get update ; \
        apt-get install -y  google-chrome-stable; \
        rm -rf /var/lib/apt/lists/* ; \
        rm -rf /etc/localtime ; \
        ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

# don't create ".bundle" in all our apps
ENV GEM_HOME /usr/local/bundle
ENV BUNDLE_PATH=/usr/local/bundle BUNDLE_BIN=/usr/local/bundle/bin BUNDLE_SILENCE_ROOT_WARNING=1 BUNDLE_APP_CONFIG=/usr/local/bundle
ENV PATH $GEM_HOME/bin:$PATH
# adjust permissions of a few directories for running "gem install" as an arbitrary user
RUN mkdir -p "$GEM_HOME" && chmod 777 "$GEM_HOME"

CMD [ "irb" ]
