FROM debian:bullseye
ENV TZ=Asia/Shanghai
ENV LANG=C.UTF-8
#上传中文字体
COPY ./customs /usr/share/fonts/truetype/customs
#安装google-chrome-stable wkhtmltopdf
RUN apt-get update; apt-get install -y --no-install-recommends 	ca-certificates curl netbase wget; \
    echo 'deb https://mirrors.aliyun.com/debian/ bullseye main non-free contribi' >/etc/apt/sources.list; \
    echo 'deb-src https://mirrors.aliyun.com/debian/ bullseye main non-free contrib' >>/etc/apt/sources.list; \
    echo 'deb https://mirrors.aliyun.com/debian-security/ bullseye-security main' >>/etc/apt/sources.list; \
    echo 'deb-src https://mirrors.aliyun.com/debian-security/ bullseye-security main' >>/etc/apt/sources.list; \
    echo 'deb https://mirrors.aliyun.com/debian/ bullseye-updates main non-free contrib' >>/etc/apt/sources.list; \
    echo 'deb-src https://mirrors.aliyun.com/debian/ bullseye-updates main non-free contrib' >>/etc/apt/sources.list; \
    echo 'deb https://mirrors.aliyun.com/debian/ bullseye-backports main non-free contrib' >>/etc/apt/sources.list; \
    echo 'deb-src https://mirrors.aliyun.com/debian/ bullseye-backports main non-free contrib' >>/etc/apt/sources.list; \
    apt-get update ;apt-get install -y  libasound2 \
                        libatk-bridge2.0-0  \
                        libatk1.0-0 \
                        libatspi2.0-0 \
                        libcairo2 \
                        libcups2 \
                        libdbus-1-3 \
                        libdrm2 \
                        libexpat1  \
                        libgbm1 \
                        libglib2.0-0 \
                        libgtk-3-0 \
                        libnspr4 \
                        libnss3 \
                        libpango-1.0-0 \
                        libwayland-client0 \
                        libx11-6 \
                        libxcb1 \
                        libxcomposite1 \
                        libxdamage1 \
                        libxext6 \
                        libxfixes3 \
                        libxkbcommon0 \
                        libxrandr2 \
                        xdg-utils \
                        libu2f-udev \
                        libvulkan1 \
                        libx11-data \
                        libfontconfig1 \
                        fonts-dejavu-core \
                        ttf-bitstream-vera \
                        fonts-liberation \
                        fonts-liberation2 \
                        fonts-croscore \
                        fonts-freefont-otf \
                        fonts-freefont-ttf \
                        fonts-urw-base35 \
                        fonts-texgyre \
                        libfontenc1 \
                        x11-common \
                        xfonts-encodings \
                        fontconfig-config \
                        libxau6 \
                        libxdmcp6 \
                        xfonts-utils \
                        fontconfig \
                        libfreetype6 \
                        libjpeg62-turbo \
                        libpng16-16 \
                        libxrender1 \
                        xfonts-75dpi \
                        xfonts-base \
                        libgeos-dev \
                        supervisor && \
    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
    wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.bullseye_amd64.deb && \
    dpkg -i google-chrome-stable_current_amd64.deb && \
    dpkg -i wkhtmltox_0.12.6.1-2.bullseye_amd64.deb && \   
    rm -rf wkhtmltox_0.12.6.1-2.bullseye_amd64.deb google-chrome-stable_current_amd64.deb; rm -rf /var/lib/apt/lists/* \
    && fc-cache && fc-list
CMD ["bash"]